# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2021  Ammar Faizi <ammarfaizi2@gmail.com>
#


OBJ_CC__kernel := \
	kernel/kernel.o

all: $(OBJ_CC)


clean:
	$(RM) -vf $(OBJ_CC)

.PHONY: all clean
